import type { WordSearchPuzzle } from '@gioguarino/wordsearch-types';

export type DailySessionData = {
  id: string;
  date: string;
  topic: string;
  puzzles: WordSearchPuzzle[];
};

export const dailySession: DailySessionData = {
  id: '2026-04-05',
  date: '2026-04-05',
  topic: 'Coffee Shop',
  puzzles: [
    {
      id: 'coffee-1',
      size: 8,
      topic: 'Coffee Shop',
      grid: [
        ['C', 'O', 'F', 'F', 'E', 'E', 'X', 'X'],
        ['X', 'X', 'X', 'X', 'X', 'X', 'X', 'X'],
        ['L', 'A', 'T', 'T', 'E', 'X', 'X', 'X'],
        ['X', 'X', 'X', 'X', 'X', 'X', 'X', 'X'],
        ['M', 'O', 'C', 'H', 'A', 'X', 'X', 'X'],
        ['X', 'X', 'X', 'X', 'X', 'X', 'X', 'X'],
        ['T', 'E', 'A', 'X', 'X', 'X', 'X', 'X'],
        ['X', 'X', 'X', 'X', 'X', 'X', 'X', 'X'],
      ],
      words: [
        { id: 'coffee', label: 'Coffee', value: 'COFFEE' },
        { id: 'latte', label: 'Latte', value: 'LATTE' },
        { id: 'mocha', label: 'Mocha', value: 'MOCHA' },
        { id: 'tea', label: 'Tea', value: 'TEA' },
      ],
      placements: [
        {
          wordId: 'coffee',
          label: 'Coffee',
          value: 'COFFEE',
          start: { row: 0, col: 0 },
          end: { row: 0, col: 5 },
          direction: 'E',
          path: [
            { row: 0, col: 0 },
            { row: 0, col: 1 },
            { row: 0, col: 2 },
            { row: 0, col: 3 },
            { row: 0, col: 4 },
            { row: 0, col: 5 },
          ],
        },
        {
          wordId: 'latte',
          label: 'Latte',
          value: 'LATTE',
          start: { row: 2, col: 0 },
          end: { row: 2, col: 4 },
          direction: 'E',
          path: [
            { row: 2, col: 0 },
            { row: 2, col: 1 },
            { row: 2, col: 2 },
            { row: 2, col: 3 },
            { row: 2, col: 4 },
          ],
        },
        {
          wordId: 'mocha',
          label: 'Mocha',
          value: 'MOCHA',
          start: { row: 4, col: 0 },
          end: { row: 4, col: 4 },
          direction: 'E',
          path: [
            { row: 4, col: 0 },
            { row: 4, col: 1 },
            { row: 4, col: 2 },
            { row: 4, col: 3 },
            { row: 4, col: 4 },
          ],
        },
        {
          wordId: 'tea',
          label: 'Tea',
          value: 'TEA',
          start: { row: 6, col: 0 },
          end: { row: 6, col: 2 },
          direction: 'E',
          path: [
            { row: 6, col: 0 },
            { row: 6, col: 1 },
            { row: 6, col: 2 },
          ],
        },
      ],
    },
    {
      id: 'coffee-2',
      size: 8,
      topic: 'Coffee Shop',
      grid: [
        ['B', 'E', 'A', 'N', 'S', 'X', 'X', 'X'],
        ['X', 'X', 'X', 'X', 'X', 'X', 'X', 'X'],
        ['M', 'I', 'L', 'K', 'X', 'X', 'X', 'X'],
        ['X', 'X', 'X', 'X', 'X', 'X', 'X', 'X'],
        ['S', 'U', 'G', 'A', 'R', 'X', 'X', 'X'],
        ['X', 'X', 'X', 'X', 'X', 'X', 'X', 'X'],
        ['C', 'A', 'K', 'E', 'X', 'X', 'X', 'X'],
        ['X', 'X', 'X', 'X', 'X', 'X', 'X', 'X'],
      ],
      words: [
        { id: 'beans', label: 'Beans', value: 'BEANS' },
        { id: 'milk', label: 'Milk', value: 'MILK' },
        { id: 'sugar', label: 'Sugar', value: 'SUGAR' },
        { id: 'cake', label: 'Cake', value: 'CAKE' },
      ],
      placements: [
        {
          wordId: 'beans',
          label: 'Beans',
          value: 'BEANS',
          start: { row: 0, col: 0 },
          end: { row: 0, col: 4 },
          direction: 'E',
          path: [
            { row: 0, col: 0 },
            { row: 0, col: 1 },
            { row: 0, col: 2 },
            { row: 0, col: 3 },
            { row: 0, col: 4 },
          ],
        },
        {
          wordId: 'milk',
          label: 'Milk',
          value: 'MILK',
          start: { row: 2, col: 0 },
          end: { row: 2, col: 3 },
          direction: 'E',
          path: [
            { row: 2, col: 0 },
            { row: 2, col: 1 },
            { row: 2, col: 2 },
            { row: 2, col: 3 },
          ],
        },
        {
          wordId: 'sugar',
          label: 'Sugar',
          value: 'SUGAR',
          start: { row: 4, col: 0 },
          end: { row: 4, col: 4 },
          direction: 'E',
          path: [
            { row: 4, col: 0 },
            { row: 4, col: 1 },
            { row: 4, col: 2 },
            { row: 4, col: 3 },
            { row: 4, col: 4 },
          ],
        },
        {
          wordId: 'cake',
          label: 'Cake',
          value: 'CAKE',
          start: { row: 6, col: 0 },
          end: { row: 6, col: 3 },
          direction: 'E',
          path: [
            { row: 6, col: 0 },
            { row: 6, col: 1 },
            { row: 6, col: 2 },
            { row: 6, col: 3 },
          ],
        },
      ],
    },
    {
      id: 'coffee-3',
      size: 8,
      topic: 'Coffee Shop',
      grid: [
        ['C', 'U', 'P', 'X', 'X', 'X', 'X', 'X'],
        ['X', 'X', 'X', 'X', 'X', 'X', 'X', 'X'],
        ['M', 'U', 'G', 'X', 'X', 'X', 'X', 'X'],
        ['X', 'X', 'X', 'X', 'X', 'X', 'X', 'X'],
        ['T', 'R', 'A', 'Y', 'X', 'X', 'X', 'X'],
        ['X', 'X', 'X', 'X', 'X', 'X', 'X', 'X'],
        ['L', 'I', 'D', 'X', 'X', 'X', 'X', 'X'],
        ['X', 'X', 'X', 'X', 'X', 'X', 'X', 'X'],
      ],
      words: [
        { id: 'cup', label: 'Cup', value: 'CUP' },
        { id: 'mug', label: 'Mug', value: 'MUG' },
        { id: 'tray', label: 'Tray', value: 'TRAY' },
        { id: 'lid', label: 'Lid', value: 'LID' },
      ],
      placements: [
        {
          wordId: 'cup',
          label: 'Cup',
          value: 'CUP',
          start: { row: 0, col: 0 },
          end: { row: 0, col: 2 },
          direction: 'E',
          path: [
            { row: 0, col: 0 },
            { row: 0, col: 1 },
            { row: 0, col: 2 },
          ],
        },
        {
          wordId: 'mug',
          label: 'Mug',
          value: 'MUG',
          start: { row: 2, col: 0 },
          end: { row: 2, col: 2 },
          direction: 'E',
          path: [
            { row: 2, col: 0 },
            { row: 2, col: 1 },
            { row: 2, col: 2 },
          ],
        },
        {
          wordId: 'tray',
          label: 'Tray',
          value: 'TRAY',
          start: { row: 4, col: 0 },
          end: { row: 4, col: 3 },
          direction: 'E',
          path: [
            { row: 4, col: 0 },
            { row: 4, col: 1 },
            { row: 4, col: 2 },
            { row: 4, col: 3 },
          ],
        },
        {
          wordId: 'lid',
          label: 'Lid',
          value: 'LID',
          start: { row: 6, col: 0 },
          end: { row: 6, col: 2 },
          direction: 'E',
          path: [
            { row: 6, col: 0 },
            { row: 6, col: 1 },
            { row: 6, col: 2 },
          ],
        },
      ],
    },
  ],
};
