import type { WordSearchPuzzle } from '@gioguarino/wordsearch-types';

export const demoPuzzle: WordSearchPuzzle = {
  id: 'coffee-demo',
  size: 8,
  topic: 'Coffee Shop',
  grid: [
    ['C', 'O', 'F', 'F', 'E', 'E', 'X', 'X'],
    ['X', 'X', 'X', 'X', 'X', 'X', 'X', 'X'],
    ['L', 'A', 'T', 'T', 'E', 'X', 'X', 'X'],
    ['X', 'X', 'X', 'X', 'X', 'X', 'X', 'X'],
    ['M', 'O', 'C', 'H', 'A', 'X', 'X', 'X'],
    ['X', 'X', 'X', 'X', 'X', 'X', 'X', 'X'],
    ['T', 'E', 'A', 'X', 'X', 'X', 'X', 'X'],
    ['X', 'X', 'X', 'X', 'X', 'X', 'X', 'X'],
  ],
  words: [
    { id: 'coffee', label: 'Coffee', value: 'COFFEE' },
    { id: 'latte', label: 'Latte', value: 'LATTE' },
    { id: 'mocha', label: 'Mocha', value: 'MOCHA' },
    { id: 'tea', label: 'Tea', value: 'TEA' },
  ],
  placements: [
    {
      wordId: 'coffee',
      label: 'Coffee',
      value: 'COFFEE',
      start: { row: 0, col: 0 },
      end: { row: 0, col: 5 },
      direction: 'E',
      path: [
        { row: 0, col: 0 },
        { row: 0, col: 1 },
        { row: 0, col: 2 },
        { row: 0, col: 3 },
        { row: 0, col: 4 },
        { row: 0, col: 5 },
      ],
    },
    {
      wordId: 'latte',
      label: 'Latte',
      value: 'LATTE',
      start: { row: 2, col: 0 },
      end: { row: 2, col: 4 },
      direction: 'E',
      path: [
        { row: 2, col: 0 },
        { row: 2, col: 1 },
        { row: 2, col: 2 },
        { row: 2, col: 3 },
        { row: 2, col: 4 },
      ],
    },
    {
      wordId: 'mocha',
      label: 'Mocha',
      value: 'MOCHA',
      start: { row: 4, col: 0 },
      end: { row: 4, col: 4 },
      direction: 'E',
      path: [
        { row: 4, col: 0 },
        { row: 4, col: 1 },
        { row: 4, col: 2 },
        { row: 4, col: 3 },
        { row: 4, col: 4 },
      ],
    },
    {
      wordId: 'tea',
      label: 'Tea',
      value: 'TEA',
      start: { row: 6, col: 0 },
      end: { row: 6, col: 2 },
      direction: 'E',
      path: [
        { row: 6, col: 0 },
        { row: 6, col: 1 },
        { row: 6, col: 2 },
      ],
    },
  ],
};
